/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 optimized-room-transformed.glb -T --typescript --types 
Files: optimized-room-transformed.glb [78.95KB] > C:\Users\hp-pc\Desktop\Mern Projects\Personal-Website\public\models\optimized-room-transformed-transformed.glb [77.4KB] (2%)
*/

import * as THREE from 'three';
import React from 'react';
import { useGLTF } from '@react-three/drei';
import type { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    _________6_blinn1_0: THREE.Mesh;
    emis_lambert1_0: THREE.Mesh;
    window4_phong1_0: THREE.Mesh;
  };
  materials: {
    blinn1: THREE.MeshStandardMaterial;
    lambert1: THREE.MeshStandardMaterial;
    phong1: THREE.MeshStandardMaterial;
  };
};

export function Room(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF(
    '/models/optimized-room-transformed-transformed.glb'
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes._________6_blinn1_0.geometry}
        material={materials.blinn1}
      />
      <mesh
        geometry={nodes.emis_lambert1_0.geometry}
        material={materials.lambert1}
      />
      <mesh
        geometry={nodes.window4_phong1_0.geometry}
        material={materials.phong1}
      />
    </group>
  );
}

useGLTF.preload('/models/optimized-room-transformed-transformed.glb');
